spring:
  security:
    user:
      name: Test
      password: Test123
  datasource:
    url: jdbc:h2:file:~db/weatherapidb
    driver-ClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        validator:
          apply_to_ddl: false
    database-platform: org.hibernate.dialect.H2Dialect
  #spring.jpa.properties.hibernate.check_nullability=true
  h2:
    console:
      enabled: true
      path: /h2-console

